import type { MarblePanelsContent, WoodProfileContent } from '@/types/site-content'

const SOTUMA = 'https://www.sotuma.tn'

export const DEFAULT_WOOD_PROFILE_CONTENT: WoodProfileContent = {
  hero: {
    eyebrow: 'Profil mural decoratif effet bois',
    headline: 'Textures',
    italic: 'et modeles reels.',
    body: 'Cette page ne montre pas de simples textures plates. Chaque reference est presentee avec les modeles disponibles pour visualiser le relief, la largeur et le rendu du profil.',
    primaryLabel: 'Voir les references',
    primaryHref: '#references',
    secondaryLabel: 'Demander prix volume',
    secondaryHref: '/contact',
    stats: [
      { label: '20', value: 'textures referencees' },
      { label: '80', value: 'images de modeles' },
      { label: '6', value: 'profils selon texture' },
      { label: 'Projet', value: 'sur devis et disponibilite' },
    ],
  },
  infoCards: [
    'Choisissez d abord la texture, puis le modele de profil.',
    'Les modeles affiches sont des images de pieces profilees, pas des swatches plats.',
    'Pour un chantier, Update Design confirme stock, quantite et prix selon reference.',
  ],
  textures: [
    { texture: '2419', name: 'Noyer Naturel', color: '#8A6E53', models: ['L24', 'L18', 'R15', 'U12', 'O15', 'P40'] },
    { texture: '2403', name: 'Chene Miel', color: '#BB895B', models: ['L24', 'L18', 'R15', 'U12', 'O15', 'P40'] },
    { texture: '2039', name: 'Gris Perle', color: '#B3AFAD', models: ['L24', 'L18', 'R15', 'U12', 'O15', 'P40'] },
    { texture: '4071', name: 'Anthracite Profond', color: '#3A4249', models: ['L24', 'L18', 'R15', 'U12', 'O15', 'P40'] },
    { texture: '4080', name: 'Gris Urbain', color: '#5D5E62', models: ['L24', 'L18', 'R15', 'U12', 'O15', 'P40'] },
    { texture: '8019', name: 'Bleu Petrole', color: '#247785', models: ['L24', 'L18', 'R15', 'U12', 'O15', 'P40'] },
    { texture: '4103', name: 'Chene Dore', color: '#C0996C', models: ['L24', 'L18', 'R15', 'U12', 'O15', 'P40'] },
    { texture: '4023', name: 'Blanc Mineral', color: '#EBEBED', models: ['L24', 'L18', 'R15', 'U12', 'O15', 'P40'] },
    { texture: '4048', name: 'Taupe Fume', color: '#7E776C', models: ['L24', 'L18', 'R15'] },
    { texture: '4051', name: 'Brun Espresso', color: '#514138', models: ['L24', 'L18', 'R15'] },
    { texture: '4075', name: 'Gris Beton', color: '#88878C', models: ['L24', 'L18', 'R15'] },
    { texture: '8027', name: 'Bleu Ardoise', color: '#576A80', models: ['L24', 'L18', 'R15'] },
    { texture: '2003', name: 'Beige Sable', color: '#C9B8A7', models: ['L24', 'L18', 'R15'] },
    { texture: '2023', name: 'Bois Rose', color: '#E5BDA2', models: ['L24', 'L18', 'R15'] },
    { texture: '4047', name: 'Chene Grise', color: '#B29A7F', models: ['L24', 'L18', 'R15'] },
    { texture: '4067', name: 'Greige Naturel', color: '#7C7369', models: ['L24', 'L18', 'R15'] },
    { texture: '4079', name: 'Graphite', color: '#464B50', models: ['L24', 'L18', 'R15'] },
    { texture: '4083', name: 'Bleu Gris', color: '#48545E', models: ['L24', 'L18', 'R15'] },
    { texture: '6033', name: 'Bleu Acier', color: '#949FAC', models: ['L24'] },
    { texture: '5033', name: 'Vert Profond', color: '#0F2B2C', models: ['L24'] },
  ],
  quality: {
    eyebrow: 'Qualite',
    headline: 'Des panneaux faits',
    italic: 'pour durer au quotidien.',
    body: 'Les qualites ci-dessous reprennent les points mis en avant dans le catalogue Sotuma: entretien simple, resistance et pose pratique pour les projets decoratifs.',
    items: [
      { image: '/sotuma/quality/features-1.jpg', title: 'Texture claire', text: 'Des materiaux selectionnes avec soin' },
      { image: '/sotuma/quality/features-2.jpg', title: 'Etanche', text: 'Facile a nettoyer' },
      { image: '/sotuma/quality/features-3.jpg', title: 'Retardateur de flamme', text: 'Non decolorant' },
      { image: '/sotuma/quality/features-4.jpg', title: 'Facile a installer', text: 'Pas besoin de colle' },
    ],
  },
  advice: {
    eyebrow: 'Conseil projet',
    headline: 'La texture donne la couleur.',
    italic: 'Le modele donne le relief.',
    points: [
      'L24 et L18 conviennent aux lignes verticales regulieres et murs continus.',
      'R15 donne un relief plus arrondi, visible sur murs TV et zones de reception.',
      'U12, O15 et P40 elargissent les possibilites pour les references disponibles en nouveau modele.',
      'Envoyez la surface et une photo: nous vous aidons a choisir texture, modele et quantite.',
    ],
    ctaLabel: 'Demander un devis',
    ctaHref: '/contact',
  },
}

export const DEFAULT_MARBLE_PANELS_CONTENT: MarblePanelsContent = {
  hero: {
    eyebrow: 'Panneaux PVC effet marbre',
    headline: 'Marbre',
    italic: 'sans masse lourde.',
    body: 'Un catalogue de panneaux muraux PVC effet marbre pense pour choisir une reference, composer les finitions et demander une proposition selon la surface du projet.',
    primaryLabel: 'Voir les references',
    primaryHref: '#references',
    secondaryLabel: 'Demander prix volume',
    secondaryHref: '/contact',
    stats: [
      { label: '13', value: 'references MB' },
      { label: '3', value: 'profils principaux' },
      { label: '6', value: 'couleurs type L' },
      { label: 'Projet', value: 'stock et devis confirmes' },
    ],
  },
  usageNotes: [
    'Halls, salons, receptions, murs TV et bureaux avec rendu pierre naturelle.',
    'Pose legere en renovation pour eviter les contraintes du marbre massif.',
    'References MB selectionnees selon couleur, veinage et ambiance du projet.',
  ],
  references: {
    eyebrow: 'References MB',
    headline: 'Choisir le veinage.',
    italic: 'Puis composer la finition.',
    body: 'Les visuels ci-dessous reprennent les references disponibles depuis le catalogue Sotuma. Chaque carte presente le code MB, une nomination claire et la famille de ton pour faciliter le choix.',
    countLabel: 'modeles',
    models: [
      { ref: 'MB004', name: 'Blanc Calacatta', tone: 'Clair', src: `${SOTUMA}/web/image/231443/MB004-.jpg` },
      { ref: 'MB007', name: 'Arabescato Gris', tone: 'Gris', src: `${SOTUMA}/web/image/163663/MB007.jpg` },
      { ref: 'MB008', name: 'Statuario Blanc', tone: 'Clair', src: `${SOTUMA}/web/image/163657/MB008.jpg` },
      { ref: 'MB010', name: 'Marbre Ivoire', tone: 'Chaud', src: `${SOTUMA}/web/image/163662/MB010.jpg` },
      { ref: 'MB012', name: 'Carrara Nuage', tone: 'Clair', src: `${SOTUMA}/web/image/163666/MB012.jpg` },
      { ref: 'MB018', name: 'Noir Saint Laurent', tone: 'Fonce', src: `${SOTUMA}/web/image/231444/MB018-.jpg` },
      { ref: 'MB019', name: 'Gris Imperial', tone: 'Gris', src: `${SOTUMA}/web/image/163668/MB019.jpg` },
      { ref: 'MB021', name: 'Onyx Beige', tone: 'Chaud', src: `${SOTUMA}/web/image/163659/MB021.jpg` },
      { ref: 'MB031', name: 'Blanc Veine Or', tone: 'Clair', src: `${SOTUMA}/web/image/163661/MB031.jpg` },
      { ref: 'MB032', name: 'Grigio Venato', tone: 'Gris', src: `${SOTUMA}/web/image/163660/MB032.jpg` },
      { ref: 'MB033', name: 'Noir Marquina', tone: 'Fonce', src: `${SOTUMA}/web/image/163665/MB033.jpg` },
      { ref: 'MB044', name: 'Travertin Dore', tone: 'Chaud', src: `${SOTUMA}/web/image/163664/MB044.jpg` },
      { ref: 'MB063', name: 'Borghini Soft', tone: 'Clair', src: `${SOTUMA}/web/image/163658/MB063.jpg` },
    ],
  },
  finishing: {
    eyebrow: 'Profils de finition',
    headline: 'Les bords comptent',
    italic: 'autant que le panneau.',
    body: 'Les accessoires permettent de traiter jonctions, angles, arrets et contours. Ils donnent au mur une finition plus nette, surtout dans les lieux professionnels.',
    accessories: [
      { type: 'Type I', text: 'Jonction droite entre deux panneaux.', src: `${SOTUMA}/web/image/160794/Accessoires-I.jpg`, detail: `${SOTUMA}/web/image/160796/Acc-typeI.png` },
      { type: 'Type T', text: 'Raccord visible pour une finition nette.', src: `${SOTUMA}/web/image/160802/Accessoires-T.jpg`, detail: `${SOTUMA}/web/image/160803/Acc-typeT.png` },
      { type: 'Type U', text: 'Encadrement et finition de bord.', src: `${SOTUMA}/web/image/160805/Accessoires-U.jpg`, detail: `${SOTUMA}/web/image/160806/Acc-typeU.png` },
    ],
    lDetailsLabel: 'Type L - 25 mm / 30 mm',
    lDetails: [
      { type: 'Type L 25 x 25', src: `${SOTUMA}/web/image/160832/Acc-typeL25.png` },
      { type: 'Type L 35 x 35', src: `${SOTUMA}/web/image/160831/Acc-typeL30.png` },
    ],
    lProfiles: [
      { name: 'Black', src: '/accessories/type-l-black.png' },
      { name: 'Purple', src: '/accessories/type-l-purple.png' },
      { name: 'Gold', src: '/accessories/type-l-gold.png' },
      { name: 'Silver', src: '/accessories/type-l-silver.png' },
      { name: 'Grey', src: '/accessories/type-l-grey.png' },
      { name: 'White', src: '/accessories/type-l-white.png' },
    ],
  },
  advice: {
    eyebrow: 'Conseil projet',
    headline: 'Le veinage donne le luxe.',
    italic: 'La finition donne la proprete.',
    points: [
      'PVC rigide avec impression haute definition effet marbre.',
      'Panneaux faciles a couper, transporter et poser sur mur existant.',
      'Profils I, T, U et L pour angles, jonctions et bordures propres.',
      'Catalogue adapte aux projets particuliers, hotels, restaurants et showrooms.',
    ],
    ctaLabel: 'Demander un devis',
    ctaHref: '/contact',
  },
  proposal: {
    image: '/editorial/marble-lobby.jpg',
    imageAlt: 'Projet interieur avec panneaux effet marbre',
    headline: 'Vous avez une surface a habiller ?',
    body: 'Envoyez les dimensions, une photo du mur et les references MB qui vous plaisent. Update Design vous propose les panneaux, profils et quantites adaptes.',
    ctaLabel: 'Recevoir une proposition',
    ctaHref: '/contact',
  },
}
